// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClUbs83BCPwhiKuana3PgQtBknQfTbtO4',
    appId: '1:1056010957856:web:7c7f01d93eb473e1287845',
    messagingSenderId: '1056010957856',
    projectId: 'push-notifications-test-bc484',
    authDomain: 'push-notifications-test-bc484.firebaseapp.com',
    storageBucket: 'push-notifications-test-bc484.firebasestorage.app',
    measurementId: 'G-QR6C9QK3ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA69pkHuUmG3SqrCPBNNhyiMhvGgw8Ru_c',
    appId: '1:1056010957856:android:3dc8a82f887d613b287845',
    messagingSenderId: '1056010957856',
    projectId: 'push-notifications-test-bc484',
    storageBucket: 'push-notifications-test-bc484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtIaAvQHT6Wd_zP1lRw7I7WcT6FZUs8KU',
    appId: '1:1056010957856:ios:791df0fe08adaac8287845',
    messagingSenderId: '1056010957856',
    projectId: 'push-notifications-test-bc484',
    storageBucket: 'push-notifications-test-bc484.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtIaAvQHT6Wd_zP1lRw7I7WcT6FZUs8KU',
    appId: '1:1056010957856:ios:791df0fe08adaac8287845',
    messagingSenderId: '1056010957856',
    projectId: 'push-notifications-test-bc484',
    storageBucket: 'push-notifications-test-bc484.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClUbs83BCPwhiKuana3PgQtBknQfTbtO4',
    appId: '1:1056010957856:web:6c6fd6ad73e09870287845',
    messagingSenderId: '1056010957856',
    projectId: 'push-notifications-test-bc484',
    authDomain: 'push-notifications-test-bc484.firebaseapp.com',
    storageBucket: 'push-notifications-test-bc484.firebasestorage.app',
    measurementId: 'G-3587RG16S5',
  );
}
